version: "3"
services:
  mysql:
    container_name: "mysql"
    hostname: "mysql"
    image: mysql/mysql-server:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dbtypegen
      MYSQL_USER: root
      MYSQL_PASSWORD: pass
    ports:
      - 3306:3306
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_general_ci",
      ]
